### ISSUE TITLE
Unable to Compile on Openbsd -- NetworkInterface.o

### ISSUE THREAD

**Issue by JasonMarkowitz** [ntop/ntopng#2355]
/mnt/remote/compiles/ntopng/include/NetworkInterface.h: In member function 'void NetworkInterface::decAlertLevel()':
/mnt/remote/compiles/ntopng/include/NetworkInterface.h:623: warning: comparison is always false due to limited range of data type
g++ -g -Wall -I/mnt/remote/compiles/ntopng -I/mnt/remote/compiles/ntopng/include -I/usr/local/include -I /mnt/remote/compiles/ntopng/third-party/hiredis -I/mnt/remote/compiles/ntopng/third-party/mongoose -I/usr/local/include/json-c -I/usr/local/include -I../nDPI/src/include -I../nDPI/src/lib/third_party/include -I/mnt/remote/compiles/ntopng/third-party/lua-5.3.5/src -DDONT_USE_LUAJIT -I/usr/local/include -I/usr/local/include -I/usr/local/include/mysql -I/usr/local/include/mysql/..  -I/mnt/remote/compiles/ntopng -I/mnt/remote/compiles/ntopng/include -I/usr/local/include -I/mnt/remote/compiles/ntopng/third-party/http-client-c/src/ -I/usr/include -I/usr/include/openssl  -DDATA_DIR='"/usr/local/share"' -I/mnt/remote/compiles/ntopng/third-party/libgeohash -I/mnt/remote/compiles/ntopng/third-party/patricia   -c src/NetworkInterface.cpp -o src/NetworkInterface.o
In file included from /mnt/remote/compiles/ntopng/include/ntop_includes.h:257,
                 from src/NetworkInterface.cpp:22:
/mnt/remote/compiles/ntopng/include/NetworkInterface.h: In member function 'void NetworkInterface::decAlertLevel()':
/mnt/remote/compiles/ntopng/include/NetworkInterface.h:623: warning: comparison is always false due to limited range of data type
src/NetworkInterface.cpp: In constructor 'NetworkInterface::NetworkInterface(const char*, const char*)':
src/NetworkInterface.cpp:74: warning: 'pcap_lookupdev' is deprecated (declared at /usr/local/include/pcap/pcap.h:327)
src/NetworkInterface.cpp:74: warning: 'pcap_lookupdev' is deprecated (declared at /usr/local/include/pcap/pcap.h:327)
src/NetworkInterface.cpp: In member function 'bool NetworkInterface::processPacket(u_int32_t, bool, const bpf_timeval*, u_int64_t, ndpi_ethhdr*, u_int16_t, ndpi_iphdr*, ndpi_ipv6hdr*, u_int16_t, u_int32_t, const pcap_pkthdr*, const u_char*, u_int16_t*, Host**, Host**, Flow**)':
src/NetworkInterface.cpp:1388: error: invalid use of incomplete type 'const struct bpf_timeval'
/mnt/remote/compiles/ntopng/include/NetworkInterface.h:397: error: forward declaration of 'const struct bpf_timeval'
src/NetworkInterface.cpp:1431: error: invalid use of incomplete type 'const struct bpf_timeval'
/mnt/remote/compiles/ntopng/include/NetworkInterface.h:397: error: forward declaration of 'const struct bpf_timeval'
src/NetworkInterface.cpp:1451: error: invalid use of incomplete type 'const struct bpf_timeval'
/mnt/remote/compiles/ntopng/include/NetworkInterface.h:397: error: forward declaration of 'const struct bpf_timeval'
src/NetworkInterface.cpp:1467: error: invalid use of incomplete type 'const struct bpf_timeval'
/mnt/remote/compiles/ntopng/include/NetworkInterface.h:397: error: forward declaration of 'const struct bpf_timeval'
src/NetworkInterface.cpp:1492: error: invalid use of incomplete type 'const struct bpf_timeval'
/mnt/remote/compiles/ntopng/include/NetworkInterface.h:397: error: forward declaration of 'const struct bpf_timeval'
src/NetworkInterface.cpp:1506: error: invalid use of incomplete type 'const struct bpf_timeval'
/mnt/remote/compiles/ntopng/include/NetworkInterface.h:397: error: forward declaration of 'const struct bpf_timeval'
src/NetworkInterface.cpp:1510: error: 'IPPROTO_SCTP' was not declared in this scope
src/NetworkInterface.cpp:1521: error: invalid use of incomplete type 'const struct bpf_timeval'
/mnt/remote/compiles/ntopng/include/NetworkInterface.h:397: error: forward declaration of 'const struct bpf_timeval'
src/NetworkInterface.cpp:1560: error: invalid use of incomplete type 'const struct bpf_timeval'
/mnt/remote/compiles/ntopng/include/NetworkInterface.h:397: error: forward declaration of 'const struct bpf_timeval'
src/NetworkInterface.cpp:1885: error: invalid use of incomplete type 'const struct bpf_timeval'
/mnt/remote/compiles/ntopng/include/NetworkInterface.h:397: error: forward declaration of 'const struct bpf_timeval'
src/NetworkInterface.cpp: In member function 'bool NetworkInterface::dissectPacket(u_int32_t, bool, u_int8_t*, const pcap_pkthdr*, const u_char*, u_int16_t*, Host**, Host**, Flow**)':
src/NetworkInterface.cpp:2311: error: no matching function for call to 'NetworkInterface::processPacket(u_int32_t&, bool&, const timeval*, u_int64_t&, ndpi_ethhdr*&, u_int16_t&, ndpi_iphdr*&, ndpi_ipv6hdr*&, unsigned int, u_int32_t&, const pcap_pkthdr*&, const u_char*&, u_int16_t*&, Host**&, Host**&, Flow**&)'
src/NetworkInterface.cpp:1357: note: candidates are: bool NetworkInterface::processPacket(u_int32_t, bool, const bpf_timeval*, u_int64_t, ndpi_ethhdr*, u_int16_t, ndpi_iphdr*, ndpi_ipv6hdr*, u_int16_t, u_int32_t, const pcap_pkthdr*, const u_char*, u_int16_t*, Host**, Host**, Flow**)
src/NetworkInterface.cpp:2447: error: no matching function for call to 'NetworkInterface::processPacket(u_int32_t&, bool&, const timeval*, u_int64_t&, ndpi_ethhdr*&, u_int16_t&, ndpi_iphdr*&, ndpi_ipv6hdr*&, unsigned int, u_int32_t&, const pcap_pkthdr*&, const u_char*&, u_int16_t*&, Host**&, Host**&, Flow**&)'
src/NetworkInterface.cpp:1357: note: candidates are: bool NetworkInterface::processPacket(u_int32_t, bool, const bpf_timeval*, u_int64_t, ndpi_ethhdr*, u_int16_t, ndpi_iphdr*, ndpi_ipv6hdr*, u_int16_t, u_int32_t, const pcap_pkthdr*, const u_char*, u_int16_t*, Host**, Host**, Flow**)
gmake: *** [Makefile:157: src/NetworkInterface.o] Error 1
#

**Comment by JasonMarkowitz** [comment]
FYI this is a build on 3.8-stable.

**Comment by emanuele-f** [comment]
You should probably search on the internet for such errors and try to figure out what to fix. I don't have a openbsd system to test this right now

**Comment by emanuele-f** [comment]
Closing for inactivity. Please provide a pull request if you improve compatibility.
