### ISSUE TITLE
Failure to compile on Rasbian 10.1

### ISSUE THREAD

**Issue by freeagent1384** [ntop/ntopng#2940]
I pulled this latest commit this morning (a208285aaba6b0d4de10980560ab39af062d1288) and ran:
$ ./autogen.sh
$ make clean
$ make
I received the below error:
src/Flow.cpp: In member function 'virtual void Flow::housekeep(time_t)':
src/Flow.cpp:2451:45: error: too many arguments to function 'ndpi_protocol ndpi_detection_giveup(ndpi_detection_module_struct*, ndpi_flow_struct*, u_int8_t)'
           get_ndpi_flow(), 1, &proto_guessed);
                                             ^
In file included from /usr/local/include/ndpi/ndpi_main.h:31,
                 from /opt/ntopng/include/ntop_includes.h:118,
                 from src/Flow.cpp:22:
/usr/local/include/ndpi/ndpi_api.h:231:17: note: declared here
   ndpi_protocol ndpi_detection_giveup(struct ndpi_detection_module_struct *ndpi_struct,
                 ^~~~~~~~~~~~~~~~~~~~~
src/Flow.cpp: In member function 'bool Flow::isLuaCallPerformed(FlowLuaCall, const timeval*)':
src/Flow.cpp:4227:72: warning: comparison of integer expressions of different signedness: 'long unsigned int' and 'const __time_t' {aka 'const long int'} [-Wsign-compare]
       return(performed_lua_calls[flow_lua_call] + periodic_update_freq > tv->tv_sec);
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
make: *** [Makefile:146: src/Flow.o] Error 1

Please let me know what other information would be helpful to you.

**Comment by lucaderi** [comment]
You need to update nDPI and try again. Recently we have changed the signature of some API calls and you seem not to have updated the code

**Comment by freeagent1384** [comment]
I pulled the latest commit (cbe20d3740c19dd59150c9764a549857902d16b8) for nDPI and went through the same process (./autogen.sh, make clean, make) then cd'ed into ntopng and again pulled the latest commit (still a208285aaba6b0d4de10980560ab39af062d1288) and ran through process (./autogen.sh, make clean, make) still ended up with the same error.

Am I going about updating improperly?

**Comment by freeagent1384** [comment]
to be certain I deleted both nDPI and ntopng and cloned fresh copies of both then tried to compile first nDPI then ntopng.  First I received:

gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o lua.o lua.c
lua.c:82:10: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [<builtin>: lua.o] Error 1
make[3]: Leaving directory '/opt/ntopng/third-party/lua-5.3.5/src'
make[2]: *** [Makefile:110: linux] Error 2
make[2]: Leaving directory '/opt/ntopng/third-party/lua-5.3.5/src'
make[1]: *** [Makefile:55: linux] Error 2
make[1]: Leaving directory '/opt/ntopng/third-party/lua-5.3.5'
make: *** [Makefile:154: /opt/ntopng/third-party/lua-5.3.5/src/liblua.a] Error 2

Then I realized I had forgotten to run $ make geoip I did a make clean, make geoip, then make again and received the same error in the initial post.

src/Flow.cpp: In member function 'virtual void Flow::housekeep(time_t)':
src/Flow.cpp:2451:45: error: too many arguments to function 'ndpi_protocol ndpi_detection_giveup(ndpi_detection_module_struct*, ndpi_flow_struct*, u_int8_t)'
           get_ndpi_flow(), 1, &proto_guessed);
                                             ^
In file included from /usr/local/include/ndpi/ndpi_main.h:31,
                 from /opt/ntopng/include/ntop_includes.h:118,
                 from src/Flow.cpp:22:
/usr/local/include/ndpi/ndpi_api.h:231:17: note: declared here
   ndpi_protocol ndpi_detection_giveup(struct ndpi_detection_module_struct *ndpi_struct,
                 ^~~~~~~~~~~~~~~~~~~~~
src/Flow.cpp: In member function 'bool Flow::isLuaCallPerformed(FlowLuaCall, const timeval*)':
src/Flow.cpp:4227:72: warning: comparison of integer expressions of different signedness: 'long unsigned int' and 'const __time_t' {aka 'const long int'} [-Wsign-compare]
       return(performed_lua_calls[flow_lua_call] + periodic_update_freq > tv->tv_sec);
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
make: *** [Makefile:146: src/Flow.o] Error 1

**Comment by emanuele-f** [comment]
Please ensure that you are using latest nDPI and ntopng dev versions (run `git pull` and recompile both nDPI and ntopng). That errors point out that you are using an old nDPI version with a newer ntopng.

**Comment by freeagent1384** [comment]
I'm sorry, I had previously run $ make install and while I was compiling the latest commit I hadn't overwrite these files.  I'm sorry for wasting your time.

**Comment by emanuele-f** [comment]
Don't worry, glad you've solved your issue
