### ISSUE TITLE
ntopng cannot build with ndpi 4.0. 

### ISSUE THREAD

**Issue by sandy-lcq** [ntop/ntopng#5848]
Hi, 
ntopng 5.0 cannot compile with ndpi 4.0,  with error:

Flow.h:337:49: error: 'ndpi_is_encrypted_proto' was not declared in this scope; did you mean 'isEncryptedProto'?
|   337 |   inline bool isEncryptedProto() const { return(ndpi_is_encrypted_proto(iface->get_ndpi_struct(), ndpiDetectedProtocol)); }
|       |                                                 ^~~~~~~~~~~~~~~~~~~~~~~
|       |                                                 isEncryptedProto

**Comment by lucaderi** [comment]
The call is present in nDPI v4 https://github.com/ntop/nDPI/blob/4.0-stable/src/include/ndpi_api.h.in#L1058

it works for me

**Comment by bsergik** [comment]
`ndpi_is_encrypted_proto` API is introduced in Aug 7, 2021. But nDPI 4.0 released on Jul 26, 2021 prior to the new API intriduction. Using latest ntop released version (5.0-Stable from zip archive) and nDIP 4.0 Stable version leads to compilation error. I guess nDPI release version should be rised prior to rising ntop version.

**Comment by araemo** [comment]
I also ran into this.  Since I was trying to build stable versions of each based on the latest _stable release_, I used [nDPI-4.0](https://github.com/ntop/nDPI/releases/tag/4.0), which as noted is missing this call (and you can see in that link, there are 4 commits to 4.0-stable since that release was cut, one of which adds this call.

Perhaps this should be a bug in nDPI instead of ntopng, but either way, this should be fixed.
