### PR TITLE
HTTPserver: fix const X509_NAME for OpenSSL 4.0

### LINKED ISSUE #10829: Build fails with OpenSSL 4.0 - const X509_NAME* in HTTPserver.cpp
ntopng 6.6 fails to build with OpenSSL 4.0.1:
  
  src/HTTPserver.cpp:413:38: error: invalid conversion from 'const X509_NAME*' to 'X509_NAME*' [-fpermissive]
  
  OpenSSL 4.0 changed X509_get_subject_name() to return `const X509_NAME*`. The fix is trivial:
  
  ```diff
  -  X509_NAME *subj = NULL;
  +  const X509_NAME *subj = NULL;
  
  Line 406 of src/HTTPserver.cpp.

### PR DESCRIPTION
**Pull request by jaipaulcheernam**
OpenSSL 4.0 changed X509_get_subject_name() to return const X509_NAME*. Update the local variable to match. This is backward-compatible with older OpenSSL versions since assigning non-const to const is always valid.

Fixes: https://github.com/ntop/ntopng/issues/10829

Please sign (check) the below before submitting the Pull Request:

- [x] I have signed the ntop Contributor License Agreement at https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md
- [x] I have read the contributing guide lines https://github.com/ntop/ntopng/blob/dev/CONTRIBUTING.md
- [x] I have updated the documentation (in doc/src/) to reflect the changes made (if applicable)

Link to the related [issue](https://github.com/ntop/ntopng/issues):

Describe changes:

### CODE REVIEW

**Comment by lucaderi** [comment]
@jaipaulcheernam Please sign CLA first

**Comment by jaipaulcheernam** [comment]
> @jaipaulcheernam Please sign CLA first

Done.

**Comment by IvanNardi** [comment]
@jaipaulcheernam, looking at the CI results, this patch broke oss-fuzz compilation

```
src/HTTPserver.cpp:540:11: error: no matching function for call to 'X509_NAME_get_text_by_NID'
  540 |           X509_NAME_get_text_by_NID(subj, NID_commonName, username,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/x509.h:802:5: note: candidate function not viable: 1st argument ('const X509_NAME *' (aka 'const struct X509_name_st *')) would lose const qualifier
  802 | int X509_NAME_get_text_by_NID(X509_NAME *name, int nid, char *buf, int len);
      |     ^                         ~~~~~~~~~~~~~~~
1 error generated.

```
Could you take a look, please?

**Comment by jaipaulcheernam** [comment]
> @jaipaulcheernam, looking at the CI results, this patch broke oss-fuzz compilation
> 
> ```
> src/HTTPserver.cpp:540:11: error: no matching function for call to 'X509_NAME_get_text_by_NID'
>   540 |           X509_NAME_get_text_by_NID(subj, NID_commonName, username,
>       |           ^~~~~~~~~~~~~~~~~~~~~~~~~
> /usr/include/openssl/x509.h:802:5: note: candidate function not viable: 1st argument ('const X509_NAME *' (aka 'const struct X509_name_st *')) would lose const qualifier
>   802 | int X509_NAME_get_text_by_NID(X509_NAME *name, int nid, char *buf, int len);
>       |     ^                         ~~~~~~~~~~~~~~~
> 1 error generated.
> ```
> 
> Could you take a look, please?

Pushed new commit , please check

**Review by IvanNardi — APPROVED** [review]
I can't test on OpenSSL 4.0, but the change seems fine to me
