### ISSUE TITLE
Compiling from source Debian 7

### ISSUE THREAD

**Issue by pcmerc** [ntop/ntopng#51]
src/NetfilterInterface.cpp: In function ‘int netfilter_callback(nfq_q_handle*, nfgenmsg*, nfq_data*, void*)’:
src/NetfilterInterface.cpp:86:64: error: invalid conversion from ‘unsigned char**’ to ‘char**’ [-fpermissive]
In file included from /usr/xxx/ntopng/include/ntop_includes.h:107:0,
                 from src/NetfilterInterface.cpp:22:
/usr/include/libnetfilter_queue/libnetfilter_queue.h:99:12: error:   initializing argument 2 of ‘int nfq_get_payload(nfq_data*, char**)’ [-fpermissive]
make: *** [src/NetfilterInterface.o] Error 1

**Comment by ariava** [comment]
@pcmerc seems that different versons of libnetfilter_queue have different prototypes for the nfq_get_payload() function. We'll discuss about this issue shortly.

**Comment by lucaderi** [comment]
@pcmerc I have just compiled on Debian 7.7 and it compiles flawlessly.

**Comment by zekicker** [comment]
I've the same issue there !

src/NetfilterInterface.cpp: In function 'int netfilter_callback(nfq_q_handle*, nfgenmsg*, nfq_data*, void*)':
src/NetfilterInterface.cpp:86: error: invalid conversion from 'unsigned char**' to 'char**'
src/NetfilterInterface.cpp:86: error:   initializing argument 2 of 'int nfq_get_payload(nfq_data*, char**)'
make: *** [src/NetfilterInterface.o] Error 1

**Comment by lucaderi** [comment]
Same as above: no problem on debian 7.7

**Comment by pcmerc** [comment]
I've removed nDPI & updated to the latest GIT version.
I've also updated to the latest version of ntopng through git.
Previous versions built no problem.

I am still receiving the same error & I'm running the latest deb 7 release.
Do I need to setup a new vm instance & prove otherwise?

**Comment by pcmerc** [comment]
Loading up a fresh instance to verify the build failure.

**Comment by pcmerc** [comment]
New compile on fresh build of debian 7.8 running now
nDPI compiled & installed prior

**Comment by pcmerc** [comment]
echo "deb http://ftp.de.debian.org/debian wheezy-backports main" > /etc/apt/sources.list.d/backports.list
apt-get update && apt-get dist-upgrade
apt-get install git screen vim build-essential devscripts libnetfilter-queue-dev autoconf libtool libpcap-dev libjson0-dev autogen automake autoconf libtool libjsoncpp-dev 
libjson-glib-dev libjson-c-dev libcurl4-openssl-dev libsqlite3-dev libgeoip-dev libxml2-dev

mkdir /usr/xxx
cd /usr/xxx
git clone https://github.com/ntop/ntopng.git
git clone https://github.com/ntop/nDPI.git

cd nDPI
./autogen.sh
./configure
make
make install

cd ../ntopng
./autogen.sh
./configure
make

Same exact error on a fresh build vm instance of Debian 7.8 w/latest updates applied

src/NetfilterInterface.cpp: In function ‘int netfilter_callback(nfq_q_handle*, nfgenmsg*, nfq_data*, void*)’:
src/NetfilterInterface.cpp:86:64: error: invalid conversion from ‘unsigned char**’ to ‘char**’ [-fpermissive]
In file included from /usr/xxx/ntopng/include/ntop_includes.h:107:0,
                 from src/NetfilterInterface.cpp:22:
/usr/include/libnetfilter_queue/libnetfilter_queue.h:99:12: error:   initializing argument 2 of ‘int nfq_get_payload(nfq_data*, char**)’ [-fpermissive]
make: *** [src/NetfilterInterface.o] Error 1


Please explain your build environment

**Comment by gav-** [comment]
Same issue, have to remove libnetfilter-queue-dev package to compile on Debian 7.8

**Comment by lucaderi** [comment]
Please send us a patch for inclusion. I do not use Debian,

**Comment by MartinAparicio** [comment]
is there any solution? I have the same problem

**Comment by lucaderi** [comment]
Said that we are working at packaging Debian .deb I see the the latest version is 8.2, so in no case we will support v7. Please start moving to 8x.

**Comment by MartinAparicio** [comment]
Thanks for the answer but I do not use Debian, I use Gentoo.

But this error is because of what? It is missing some plug upgrade? Or the version of the kernel?

regards

**Comment by lucaderi** [comment]
Your netfilter library is too old as the API has changed. We cannot support all Linux distro and multiple versions of them. You need to help yourself and send us a patch, or move to a distribution we use and support.

**Comment by pcmerc** [comment]
I was able to get it working on 7 by building an updated deb for a dependency.

Works for me on both 7 & 8 :D


John~

**Comment by lucaderi** [comment]
Note that we release Debian 8 binaries: http://packages.ntop.org/apt/
