### ISSUE TITLE
Issue with DKMS and Module pfRing

### ISSUE THREAD

**Issue by animosity022** [ntop/ntopng#1033]
I'm seeing the following issue when I do my updates:

```
dpkg-reconfigure pfring-dkms

------------------------------
Deleting module version: 6.5.0
completely from the DKMS tree.
------------------------------
Done.
Loading new pfring-6.5.0 DKMS files...
First Installation: checking all kernels...
Building only for 4.2.0-27-generic
Building for architecture x86_64
Building initial module for 4.2.0-27-generic
ERROR (dkms apport): kernel package linux-headers-4.2.0-27-generic is not supported
Error! Bad return status for module build on kernel: 4.2.0-27-generic (x86_64)
Consult /var/lib/dkms/pfring/6.5.0/build/make.log for more information.
```

Make Log File
```
root@plex: ~# cat /var/lib/dkms/pfring/6.5.0/build/make.log
DKMS make.log for pfring-6.5.0 for kernel 4.2.0-27-generic (x86_64)
Wed Mar  8 09:06:54 EST 2017
make -C /lib/modules/4.2.0-27-generic/build SUBDIRS=/var/lib/dkms/pfring/6.5.0/build EXTRA_CFLAGS='-I/var/lib/dkms/pfring/6.5.0/build -DGIT_REV="\"dev:2fc44ff71cf632764ee3db312445bc25d707820c\""' modules
make[1]: Entering directory '/usr/src/linux-headers-4.2.0-27-generic'
arch/x86/Makefile:123: stack-protector enabled but compiler support broken
Makefile:669: Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
  CC [M]  /var/lib/dkms/pfring/6.5.0/build/pf_ring.o
/var/lib/dkms/pfring/6.5.0/build/pf_ring.c:1:0: error: code model kernel does not support PIC mode
 /* ***************************************************************

scripts/Makefile.build:264: recipe for target '/var/lib/dkms/pfring/6.5.0/build/pf_ring.o' failed
make[2]: *** [/var/lib/dkms/pfring/6.5.0/build/pf_ring.o] Error 1
Makefile:1398: recipe for target '_module_/var/lib/dkms/pfring/6.5.0/build' failed
make[1]: *** [_module_/var/lib/dkms/pfring/6.5.0/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.2.0-27-generic'
Makefile:48: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by cardigliano** [comment]
@animosity22 what OS are you running?

**Comment by animosity022** [comment]
```
 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Zesty Zapus (development branch)
Release:	17.04
Codename:	zesty
felix@plex: ~$
```

**Comment by cardigliano** [comment]
@animosity22 we support ubuntu LTS only, Ubuntu 17 is untested, we will do the porting ASAP, however please note this is low priority for us.

**Comment by animosity022** [comment]
I'll close it out then as I was going to migrate back to a LTS only version tonight as I thought it was most likely related to that. No reason to troubleshoot for me.

Thanks for the quick update.
