### ISSUE TITLE
latest stable ntopng (3.8) does not compile against latest stable libndpi (2.8)

### ISSUE THREAD

**Issue by cavedon** [ntop/ntopng#3143]
The latest stable release of ntopng in https://github.com/ntop/ntopng/releases (3.8) fails to compile against the latest stable release of libndpi in https://github.com/ntop/ndpi/releases (2.8).

```
g++ -g -Wall -I/home/cavedon/debian/ntopng.git -I/home/cavedon/debian/ntopng.git/include -I/usr/local/include -D_FILE_OFFSET_BITS=64 -I/usr/include/hiredis -I/usr/include/hiredis -I/home/cavedon/debian/ntopng.git/third-party/mongoose -I/usr/include/json-c  -I../nDPI/src/include -I../nDPI/src/lib/third_party/include -I/home/cavedon/debian/ntopng.git/third-party/lua-5.3.5/src -DDONT_USE_LUAJIT   -I/usr/include/mysql  -I/home/cavedon/debian/ntopng.git -I/home/cavedon/debian/ntopng.git/include -I/usr/local/include -I/home/cavedon/debian/ntopng.git/third-party/http-client-c/src/  -I/usr/include/openssl  -DDATA_DIR='"/usr/local/share"' -I/home/cavedon/debian/ntopng.git/third-party/libgeohash -I/home/cavedon/debian/ntopng.git/third-party/patricia   -c src/NetworkInterface.cpp -o src/NetworkInterface.o
src/NetworkInterface.cpp: In member function ‘bool NetworkInterface::processPacket(u_int32_t, bool, const timeval*, u_int64_t, ndpi_ethhdr*, u_int16_t, ndpi_iphdr*, ndpi_ipv6hdr*, u_int16_t, u_int32_t, const pcap_pkthdr*, const u_char*, u_int16_t*, Host**, Host**, Flow**)’:
src/NetworkInterface.cpp:1607:50: error: invalid conversion from ‘ndpi_iphdr*’ to ‘u_int32_t {aka unsigned int}’ [-fpermissive]
      ndpi_fill_ip_protocol_category(ndpi_struct, (struct ndpi_iphdr *)ip, &icmp_proto);
                                                  ^~~~~~~~~~~~~~~~~~~~~~~
src/NetworkInterface.cpp:1607:75: error: invalid conversion from ‘ndpi_protocol* {aka ndpi_proto*}’ to ‘u_int32_t {aka unsigned int}’ [-fpermissive]
      ndpi_fill_ip_protocol_category(ndpi_struct, (struct ndpi_iphdr *)ip, &icmp_proto);
                                                                           ^~~~~~~~~~~
src/NetworkInterface.cpp:1607:86: error: too few arguments to function ‘int ndpi_fill_ip_protocol_category(ndpi_detection_module_struct*, u_int32_t, u_int32_t, ndpi_protocol*)’
      ndpi_fill_ip_protocol_category(ndpi_struct, (struct ndpi_iphdr *)ip, &icmp_proto);
                                                                                      ^
In file included from ../nDPI/src/include/ndpi_main.h:31:0,
                 from /home/cavedon/debian/ntopng.git/include/ntop_includes.h:112,
                 from src/NetworkInterface.cpp:22:
../nDPI/src/include/ndpi_api.h:742:7: note: declared here
   int ndpi_fill_ip_protocol_category(struct ndpi_detection_module_struct *ndpi_struct,
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:157: recipe for target 'src/NetworkInterface.o' failed

```

I encountered this issue while trying to upgrade libndpi from 2.6 to 2.8 in Debian.

**Comment by simonemainardi** [comment]
Latest stable nDPI is 3.0 (https://github.com/ntop/nDPI/tree/3.0-stable) which successfully builds with ntopng 3.8.

I've added the release at https://github.com/ntop/nDPI/releases

**Comment by lucaderi** [comment]
See https://github.com/ntop/ntopng/blob/3.8-stable/.travis.yml for compilation hints

**Comment by cavedon** [comment]
> I've added the release at https://github.com/ntop/nDPI/releases

Thank you for adding nDPI 3.0 to the releases.
However ntopng 3.8 in the [Releases](https://github.com/ntop/ntopng/releases) page does not build with nDPI 3.0 either (see error below).

If instead I build from the `3.8-stable` branch, then it builds successfully. Would you consider adding that to the releases, please, e.g. as 3.8.1? 

Thank you.

nDPI release 3.0 + ntopng release 3.8:
```
In file included from /home/cavedon/debian/ntopng.git/include/ntop_includes.h:316:0,
                 from src/PF_RINGInterface.cpp:22:
/home/cavedon/debian/ntopng.git/include/Flow.h: In member function ‘bool Flow::isSSL()’:
/home/cavedon/debian/ntopng.git/include/Flow.h:251:57: error: ‘NDPI_PROTOCOL_SSL’ was not declared in this scope
   inline bool isSSL()                  { return(isProto(NDPI_PROTOCOL_SSL));  }
                                                         ^~~~~~~~~~~~~~~~~
/home/cavedon/debian/ntopng.git/include/Flow.h:251:57: note: suggested alternative: ‘NDPI_PROTOCOL_SSH’
   inline bool isSSL()                  { return(isProto(NDPI_PROTOCOL_SSL));  }
                                                         ^~~~~~~~~~~~~~~~~
                                                         NDPI_PROTOCOL_SSH
Makefile:157: recipe for target 'src/PF_RINGInterface.o' failed
```

**Comment by simonemainardi** [comment]
done

**Comment by cavedon** [comment]
Thank you, very appreciated.
