### ISSUE TITLE
Compiling ntopng-4.0/rrdtool-1.4.8 from source with glib-2.64

### ISSUE THREAD

**Issue by peterneutron** [ntop/ntopng#3691]
**Description:**

_**ntopng-4.0**_ fails to build on system running **_glib-2.64_** in combination with _**rrdtool-1.4.8**_ as provided in third-party.

`/usr/bin/ld: rrdcached-rrd_daemon.o: undefined reference to symbol 'g_tree_lookup'
/usr/bin/ld: /usr/lib/libglib-2.0.so.0: error adding symbols: DSO missing from command line`

**Steps to reproduce:**

Try building ntopng-4.0 with glib-2.64.

**Possible solution:**

I also tried to compile standalone _**rrdtool-1.4.8**_ from source with the same error. Using _**rrdtool-1.7.2**_ however doesn't produce an error so i suggest to bump the included rrdtool to a newer one.

**Comment by simonemainardi** [comment]
Can you install librrd using you package manager so ntopng will figure it out and dynamically link to it (see https://github.com/ntop/ntopng/blob/dev/doc/README.compilation)?

Won't be able to bump the third-party as it's used to build on very old systems. Dynamically linked librrd is used almost everywhere and should be preferred as explained in the redme linked above.

**Comment by peterneutron** [comment]
Can confirm dynamically linked librrd fixes the issues. I just forgot to add librrd as dependency, it was a custom build package. Thanks for pointing me in the right direction.
